[package]
name = "log_generator_crate"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
rand = "0.8.5"
anyhow = "1.0.86"
colored = "2.1.0"